### ISSUE TITLE
Problem with code "incompatible import/export statement used in *.js" ?

### ISSUE THREAD

**Issue by rajanjitenpatel** [topcoderinc/Topcoder-StarterPack_BluemixNode#10]
**command line:-**
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (3.6M)
Uploaded droplet (18.7M)
Uploading complete
Destroying container
Successfully destroyed container

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 crashed
FAILED
Error restarting application: Start unsuccessful
------------------------------------------------------------------------------

**Log ( cf logs <appname> --recent)**

2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR /home/vcap/app/src/app.js:5
2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR import express from 'express'; 
2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR ^^^^^^
2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR SyntaxError: Unexpected token import
2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR     at createScript (vm.js:56:10)
2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR     at Object.runInThisContext (vm.js:97:10)
 2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:542:28)
 2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR     at loader (/home/vcap/app/node_modules/babel-register/lib/node.js:144:5)
 2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR     at Object.require.extensions.(anonymous function) [as .js] (/home/vcap/app/node_modules/babel-register/lib/node.js:154:7)
   2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR     at Module.load (module.js:487:32)
   2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:446:12)
   2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:438:3)
   2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR     at Function.Module.runMain (module.js:604:10)
   2017-07-08T10:21:28.03+0530 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/node_modules/babel-cli/lib/_babel-node.js:154:22)
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! Linux 4.4.0-75-generic
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! node v6.10.2
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! npm  v3.10.10
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! bluemix-starter@1.0.0 start: `better-npm-run start`
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! 
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! Failed at the bluemix-starter@1.0.0 start script 'better-npm-run start'.
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! Make sure you have the latest version of node.js and npm installed.
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! If you do, this is most likely a problem with the bluemix-starter package,
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! not with npm itself.
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! Tell the author that this fails on your system:
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR!     better-npm-run start
   2017-07-08T10:21:28.07+0530 [APP/PROC/WEB/0] ERR npm ERR! You can get information on how to open an issue for this project with:
   2017-07-08T10:21:28.08+0530 [APP/PROC/WEB/0] ERR npm ERR!     npm bugs bluemix-starter
   2017-07-08T10:21:28.08+0530 [APP/PROC/WEB/0] ERR npm ERR! Or if that isn't available, you can get their info via:
   2017-07-08T10:21:28.08+0530 [APP/PROC/WEB/0] ERR npm ERR!     npm owner ls bluemix-starter
   2017-07-08T10:21:28.08+0530 [APP/PROC/WEB/0] ERR npm ERR! There is likely additional logging output above.
   2017-07-08T10:21:28.08+0530 [APP/PROC/WEB/0] ERR npm ERR! Please include the following file with any support request:
   2017-07-08T10:21:28.08+0530 [APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/npm-debug.log

---------------------------------------------------------------------
ref link:-
https://stackoverflow.com/questions/39436322/node-js-syntaxerror-unexpected-token-import/39436379.

**Comment by rajanjitenpatel** [comment]
I am sorry.
no Issue is there in code..
